#!/usr/bin/env bash
# Shared helpers for docs/memory/*.sh — safe env parse (never source).
# shellcheck shell=bash

# Allowlisted keys only (no PATH / PYTHONPATH injection).
MEMORY_ENV_KEYS=(
  CHUNKHOUND_MEMORY_DIR
  CHUNKHOUND_MEMORY_TOKEN
  CHUNKHOUND_MEMORY_HOST
  CHUNKHOUND_MEMORY_PORT
  CHUNKHOUND_MEMORY_PUBLIC_HOST
)

memory_key_allowed() {
  local key="$1"
  local k
  for k in "${MEMORY_ENV_KEYS[@]}"; do
    if [[ "$k" == "$key" ]]; then
      return 0
    fi
  done
  return 1
}

resolve_repo_root() {
  local script_dir="$1"
  if [[ -n "${CHUNKHOUND_REPO:-}" ]]; then
    if [[ -f "${CHUNKHOUND_REPO}/pyproject.toml" ]]; then
      cd "${CHUNKHOUND_REPO}" && pwd
      return 0
    fi
    echo "ERROR: CHUNKHOUND_REPO=${CHUNKHOUND_REPO} has no pyproject.toml" >&2
    return 1
  fi
  local cand
  cand="$(cd "${script_dir}/../.." && pwd)"
  if [[ -f "${cand}/pyproject.toml" ]]; then
    echo "$cand"
    return 0
  fi
  # Walk parents looking for pyproject.toml
  local d="$script_dir"
  while [[ "$d" != "/" ]]; do
    if [[ -f "${d}/pyproject.toml" ]]; then
      echo "$d"
      return 0
    fi
    d="$(cd "$d/.." && pwd)"
  done
  echo "ERROR: cannot find ChunkHound repo (pyproject.toml). Set CHUNKHOUND_REPO." >&2
  return 1
}

# Load allowlisted KEY=value lines into named variables via nameref map.
# Usage: load_memory_env_file /path/to/memory-serve.env
# Sets shell vars with the same names for allowed keys found.
load_memory_env_file() {
  local file="$1"
  local line key value
  if [[ ! -f "$file" ]]; then
    return 0
  fi
  while IFS= read -r line || [[ -n "$line" ]]; do
    # strip CR (Windows)
    line="${line%$'\r'}"
    # trim leading/trailing whitespace
    line="${line#"${line%%[![:space:]]*}"}"
    line="${line%"${line##*[![:space:]]}"}"
    [[ -z "$line" || "$line" == \#* ]] && continue
    if [[ "$line" != *=* ]]; then
      echo "WARNING: ignoring invalid env line in $file: $line" >&2
      continue
    fi
    key="${line%%=*}"
    value="${line#*=}"
    key="${key%"${key##*[![:space:]]}"}"
    key="${key#"${key%%[![:space:]]*}"}"
    # strip optional surrounding quotes
    if [[ "$value" == \"*\" && "$value" == *\" ]]; then
      value="${value:1:${#value}-2}"
    elif [[ "$value" == \'*\' && "$value" == *\' ]]; then
      value="${value:1:${#value}-2}"
    fi
    if ! memory_key_allowed "$key"; then
      echo "WARNING: ignoring non-allowlisted key in $file: $key" >&2
      continue
    fi
    # Reject values that would have been shell-active if sourced
    if [[ "$value" == *$'\n'* || "$value" == *$'\0'* ]]; then
      echo "ERROR: invalid value for $key in $file (newline/null)" >&2
      return 1
    fi
    printf -v "$key" '%s' "$value"
  done <"$file"
}

# Write allowlisted KEY=value (unquoted; values must not contain newlines).
# Usage: write_memory_env_file /path/to/file
# Reads CHUNKHOUND_MEMORY_* from current shell environment.
write_memory_env_file() {
  local file="$1"
  local key value
  {
    echo "# Generated by ChunkHound memory setup — KEY=value, no shell syntax"
    echo "# Loaded with a strict parser (never sourced). Allowlisted keys only."
    for key in "${MEMORY_ENV_KEYS[@]}"; do
      value="${!key-}"
      if [[ -z "$value" ]]; then
        continue
      fi
      if [[ "$value" == *$'\n'* ]]; then
        echo "ERROR: $key value contains newline" >&2
        return 1
      fi
      # No quotes: parsers strip optional quotes; unquoted is canonical.
      printf '%s=%s\n' "$key" "$value"
    done
  } >"$file"
  chmod 600 "$file" 2>/dev/null || true
}

validate_port() {
  local port="$1"
  if [[ ! "$port" =~ ^[0-9]+$ ]] || ((port < 1 || port > 65535)); then
    echo "ERROR: invalid port '$port' (need 1-65535)" >&2
    return 1
  fi
}

restrict_file_mode() {
  local f="$1"
  chmod 600 "$f" 2>/dev/null || true
}
