# Shared helpers for docs/memory/*.ps1 — safe env parse (allowlist only).

$script:MemoryEnvKeys = @(
    "CHUNKHOUND_MEMORY_DIR",
    "CHUNKHOUND_MEMORY_TOKEN",
    "CHUNKHOUND_MEMORY_HOST",
    "CHUNKHOUND_MEMORY_PORT",
    "CHUNKHOUND_MEMORY_PUBLIC_HOST"
)

function Resolve-ChunkHoundRepoRoot {
    param([string]$ScriptDir)
    if ($env:CHUNKHOUND_REPO) {
        $cand = $env:CHUNKHOUND_REPO
        if (Test-Path (Join-Path $cand "pyproject.toml")) {
            return (Resolve-Path $cand).Path
        }
        throw "CHUNKHOUND_REPO=$cand has no pyproject.toml"
    }
    $cand = (Resolve-Path (Join-Path $ScriptDir "..\..")).Path
    if (Test-Path (Join-Path $cand "pyproject.toml")) {
        return $cand
    }
    $d = $ScriptDir
    while ($d) {
        if (Test-Path (Join-Path $d "pyproject.toml")) {
            return $d
        }
        $parent = Split-Path -Parent $d
        if ($parent -eq $d) { break }
        $d = $parent
    }
    throw "Cannot find ChunkHound repo (pyproject.toml). Set CHUNKHOUND_REPO."
}

function Read-MemoryEnvFile {
    <#
    .SYNOPSIS
      Parse memory-serve.env; return hashtable of allowlisted keys only.
    #>
    param([Parameter(Mandatory)][string]$Path)
    $result = @{}
    if (-not (Test-Path $Path)) { return $result }
    Get-Content -LiteralPath $Path | ForEach-Object {
        $line = $_.Trim()
        if (-not $line -or $line.StartsWith("#")) { return }
        $idx = $line.IndexOf("=")
        if ($idx -lt 1) {
            Write-Warning "Ignoring invalid env line: $line"
            return
        }
        $key = $line.Substring(0, $idx).Trim()
        $value = $line.Substring($idx + 1)
        if ($value.Length -ge 2) {
            $q = $value[0]
            if (($q -eq [char]34 -or $q -eq [char]39) -and $value[-1] -eq $q) {
                $value = $value.Substring(1, $value.Length - 2)
            }
        }
        if ($script:MemoryEnvKeys -notcontains $key) {
            Write-Warning "Ignoring non-allowlisted key: $key"
            return
        }
        if ($value -match "[\r\n]") {
            throw "Invalid value for $key (newline not allowed)"
        }
        $result[$key] = $value
    }
    return $result
}

function Write-MemoryEnvFile {
    param(
        [Parameter(Mandatory)][string]$Path,
        [Parameter(Mandatory)][hashtable]$Values
    )
    $lines = @(
        "# Generated by ChunkHound memory setup - KEY=value, no shell syntax",
        "# Loaded with a strict parser (never executed). Allowlisted keys only."
    )
    foreach ($key in $script:MemoryEnvKeys) {
        if (-not $Values.ContainsKey($key)) { continue }
        $value = [string]$Values[$key]
        if (-not $value) { continue }
        if ($value -match "[\r\n]") {
            throw "$key value contains newline"
        }
        $lines += "$key=$value"
    }
    # UTF-8 no BOM
    $utf8 = New-Object System.Text.UTF8Encoding $false
    [System.IO.File]::WriteAllLines($Path, $lines, $utf8)
    Restrict-FileAcl -Path $Path
}

function Restrict-FileAcl {
    param([Parameter(Mandatory)][string]$Path)
    if (-not (Test-Path $Path)) { return }
    try {
        $sid = [System.Security.Principal.WindowsIdentity]::GetCurrent().User.Value
        # Prefer SID; fall back to username if SID grant fails on this host.
        $prev = $ErrorActionPreference
        $ErrorActionPreference = "Continue"
        $out = & icacls.exe $Path /inheritance:r /grant:r "*${sid}:(R,W)" 2>&1
        $code = $LASTEXITCODE
        if ($code -ne 0) {
            $out = & icacls.exe $Path /inheritance:r /grant:r "$env:USERNAME:(R,W)" 2>&1
            $code = $LASTEXITCODE
        }
        $ErrorActionPreference = $prev
        if ($code -ne 0) {
            Write-Warning "Could not restrict ACL on $Path (exit $code): $out"
        }
    } catch {
        Write-Warning "Could not restrict ACL on $Path : $_"
    }
}

function Test-MemoryPort {
    param([string]$Port)
    $n = 0
    if (-not [int]::TryParse($Port, [ref]$n)) { return $false }
    return ($n -ge 1 -and $n -le 65535)
}

function Merge-EmbeddingConfig {
    <#
    .SYNOPSIS
      Merge embedding into .chunkhound.json via Python (no BOM / ConvertTo-Json issues).
    #>
    param(
        [Parameter(Mandatory)][string]$ConfigPath,
        [Parameter(Mandatory)][string]$Provider,
        [Parameter(Mandatory)][string]$ApiKey,
        [Parameter(Mandatory)][string]$Model
    )
    $env:CHUNKHOUND_SETUP_EMBED_PROVIDER = $Provider
    $env:CHUNKHOUND_SETUP_EMBED_API_KEY = $ApiKey
    $env:CHUNKHOUND_SETUP_EMBED_MODEL = $Model
    $env:CHUNKHOUND_SETUP_EMBED_CONFIG = $ConfigPath
    try {
        python -c @"
import json, os
from pathlib import Path
path = Path(os.environ['CHUNKHOUND_SETUP_EMBED_CONFIG'])
data = json.loads(path.read_text(encoding='utf-8'))
data['embedding'] = {
    'provider': os.environ['CHUNKHOUND_SETUP_EMBED_PROVIDER'],
    'api_key': os.environ['CHUNKHOUND_SETUP_EMBED_API_KEY'],
    'model': os.environ['CHUNKHOUND_SETUP_EMBED_MODEL'],
}
path.write_text(json.dumps(data, indent=2) + '\n', encoding='utf-8')
print(f\"Updated embedding in {path}\")
"@
        if ($LASTEXITCODE -ne 0) {
            throw "Python failed to update embedding config (exit $LASTEXITCODE)"
        }
    } finally {
        Remove-Item Env:CHUNKHOUND_SETUP_EMBED_PROVIDER -ErrorAction SilentlyContinue
        Remove-Item Env:CHUNKHOUND_SETUP_EMBED_API_KEY -ErrorAction SilentlyContinue
        Remove-Item Env:CHUNKHOUND_SETUP_EMBED_MODEL -ErrorAction SilentlyContinue
        Remove-Item Env:CHUNKHOUND_SETUP_EMBED_CONFIG -ErrorAction SilentlyContinue
    }
    Restrict-FileAcl -Path $ConfigPath
}
