#!/usr/bin/env bash
# Interactive setup for ChunkHound Memory (init + embeddings + env + client configs).
# Usage: ./setup.sh
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="$(cd "$SCRIPT_DIR/../.." && pwd)"

prompt() {
  local msg="$1"
  local default="${2:-}"
  local value=""
  if [[ -n "$default" ]]; then
    read -r -p "$msg [$default]: " value
    echo "${value:-$default}"
  else
    read -r -p "$msg: " value
    echo "$value"
  fi
}

prompt_secret() {
  local msg="$1"
  local value=""
  read -r -s -p "$msg: " value
  echo "" >&2
  echo "$value"
}

yes_no() {
  local msg="$1"
  local default="${2:-y}"
  local yn
  read -r -p "$msg [y/n] (default $default): " yn
  yn="${yn:-$default}"
  [[ "$yn" =~ ^[Yy] ]]
}

echo "============================================================"
echo " ChunkHound Memory — interactive setup"
echo "============================================================"
echo "Repo: $REPO_ROOT"
echo ""

if ! command -v uv >/dev/null 2>&1; then
  echo "ERROR: 'uv' not found. Install: https://docs.astral.sh/uv/"
  echo "Manual: curl -LsSf https://astral.sh/uv/install.sh | sh"
  exit 1
fi

DEFAULT_DIR="$HOME/.chunkhound-memory"
MEMORY_DIR="$(prompt "Memory directory" "$DEFAULT_DIR")"
MEMORY_DIR="${MEMORY_DIR/#\~/$HOME}"
mkdir -p "$MEMORY_DIR"
MEMORY_DIR="$(cd "$MEMORY_DIR" && pwd)"

echo ""
echo "→ Initializing memory directory..."
cd "$REPO_ROOT"
uv run chunkhound memory init --dir "$MEMORY_DIR"

CONFIG="$MEMORY_DIR/.chunkhound.json"
if [[ ! -f "$CONFIG" ]]; then
  echo "ERROR: expected $CONFIG after init."
  exit 1
fi

echo ""
echo "Embedding provider (required for semantic recall)"
echo "  1) openai"
echo "  2) voyageai"
echo "  3) skip (configure $CONFIG manually later)"
PROVIDER_CHOICE="$(prompt "Choice" "1")"
case "$PROVIDER_CHOICE" in
  1|openai) PROVIDER="openai" ;;
  2|voyageai) PROVIDER="voyageai" ;;
  3|skip|"") PROVIDER="" ;;
  *) PROVIDER="$PROVIDER_CHOICE" ;;
esac

if [[ -n "$PROVIDER" ]]; then
  MODEL_DEFAULT="text-embedding-3-small"
  if [[ "$PROVIDER" == "voyageai" ]]; then
    MODEL_DEFAULT="voyage-3"
  fi
  MODEL="$(prompt "Embedding model" "$MODEL_DEFAULT")"
  API_KEY="$(prompt_secret "API key for $PROVIDER (input hidden)")"
  if [[ -z "$API_KEY" ]]; then
    echo "No API key entered — leaving embedding config unchanged."
  else
    python3 - "$CONFIG" "$PROVIDER" "$API_KEY" "$MODEL" <<'PY'
import json, sys
from pathlib import Path
path, provider, api_key, model = Path(sys.argv[1]), sys.argv[2], sys.argv[3], sys.argv[4]
data = json.loads(path.read_text(encoding="utf-8"))
data["embedding"] = {
    "provider": provider,
    "api_key": api_key,
    "model": model,
}
path.write_text(json.dumps(data, indent=2) + "\n", encoding="utf-8")
print(f"Updated embedding provider={provider} model={model} in {path}")
PY
  fi
else
  echo ""
  echo "MANUAL: edit $CONFIG and add an \"embedding\" block, then re-index."
fi

echo ""
if yes_no "Re-index memory directory with embeddings now?" "y"; then
  echo "→ Indexing (may take a minute)..."
  uv run chunkhound index "$MEMORY_DIR" \
    --config "$CONFIG" \
    --db "$MEMORY_DIR/.chunkhound/db" || {
      echo "Index failed. Fix embeddings/config and run:"
      echo "  uv run chunkhound index \"$MEMORY_DIR\" --config \"$CONFIG\" --db \"$MEMORY_DIR/.chunkhound/db\""
    }
else
  echo "MANUAL later:"
  echo "  uv run chunkhound index \"$MEMORY_DIR\" --config \"$CONFIG\" --db \"$MEMORY_DIR/.chunkhound/db\""
fi

echo ""
echo "LAN serve settings"
HOST="$(prompt "Bind host (0.0.0.0 = all interfaces)" "0.0.0.0")"
PORT="$(prompt "Port" "8765")"
if [[ -n "${CHUNKHOUND_MEMORY_TOKEN:-}" ]]; then
  TOKEN="$CHUNKHOUND_MEMORY_TOKEN"
  echo "Using existing CHUNKHOUND_MEMORY_TOKEN from environment."
else
  if yes_no "Generate a random API token?" "y"; then
    if command -v openssl >/dev/null 2>&1; then
      TOKEN="$(openssl rand -hex 32)"
    else
      TOKEN="$(python3 -c 'import secrets; print(secrets.token_hex(32))')"
    fi
    echo "Generated token (store safely): $TOKEN"
  else
    TOKEN="$(prompt_secret "Enter token (input hidden)")"
  fi
fi

PUBLIC_HOST="$(prompt "Hostname/IP other machines should use (for printed configs)" "127.0.0.1")"

ENV_FILE="$MEMORY_DIR/memory-serve.env"
# Values quoted for paths with spaces; serve.sh sources this file.
cat > "$ENV_FILE" <<EOF
# Generated by docs/memory/setup.sh — used by serve.sh / serve.ps1
CHUNKHOUND_MEMORY_DIR="$MEMORY_DIR"
CHUNKHOUND_MEMORY_TOKEN="$TOKEN"
CHUNKHOUND_MEMORY_HOST="$HOST"
CHUNKHOUND_MEMORY_PORT="$PORT"
CHUNKHOUND_MEMORY_PUBLIC_HOST="$PUBLIC_HOST"
EOF
chmod 600 "$ENV_FILE" 2>/dev/null || true
echo "Wrote $ENV_FILE"

echo ""
echo "→ Client configuration snippets:"
export CHUNKHOUND_MEMORY_TOKEN="$TOKEN"
export CHUNKHOUND_MEMORY_PORT="$PORT"
export CHUNKHOUND_MEMORY_PUBLIC_HOST="$PUBLIC_HOST"
bash "$SCRIPT_DIR/client-config.sh" --host "$PUBLIC_HOST" --port "$PORT" --token "$TOKEN"

echo ""
echo "============================================================"
echo " Next steps"
echo "============================================================"
echo "1. Start the server on this host:"
echo "     $SCRIPT_DIR/serve.sh"
echo "   (or: bash $SCRIPT_DIR/serve.sh --dir \"$MEMORY_DIR\")"
echo ""
echo "2. MANUAL — open firewall TCP $PORT if other PCs will connect."
echo ""
echo "3. MANUAL — paste client JSON into each harness (Claude Code, Cursor,"
echo "   Grok Build, etc.) using the snippets printed above."
echo "   Claude Code can use the printed 'claude mcp add' command."
echo ""
echo "4. Do NOT also run 'chunkhound memory mcp' on the same directory while"
echo "   serve is running. All clients (including this PC) use HTTP."
echo ""
echo "5. Optional LLM for better memory_research summaries: edit $CONFIG"
echo "   and add an \"llm\" block (see chunkhound.ai configuration docs)."
echo ""
if yes_no "Start memory serve now?" "n"; then
  exec bash "$SCRIPT_DIR/serve.sh" --dir "$MEMORY_DIR" --host "$HOST" --port "$PORT" --token "$TOKEN"
fi

echo "Done. Full guide: docs/memory-setup.md"
